// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXj__o2m_TdriPx8iPRW71EEGyFAZOG9c',
    appId: '1:1072889993116:android:00dacbda84eb9b6f3a9a59',
    messagingSenderId: '1072889993116',
    projectId: 'yakin-b80cf',
    storageBucket: 'yakin-b80cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuAjKFAN3JZ_jB3e4XAvoPwzq0keQkM_Y',
    appId: '1:1072889993116:ios:3ad47ef7316001a53a9a59',
    messagingSenderId: '1072889993116',
    projectId: 'yakin-b80cf',
    storageBucket: 'yakin-b80cf.firebasestorage.app',
    iosBundleId: 'com.example.yakinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuAjKFAN3JZ_jB3e4XAvoPwzq0keQkM_Y',
    appId: '1:1072889993116:ios:3ad47ef7316001a53a9a59',
    messagingSenderId: '1072889993116',
    projectId: 'yakin-b80cf',
    storageBucket: 'yakin-b80cf.firebasestorage.app',
    iosBundleId: 'com.example.yakinApp',
  );
}
